.gitattributes
.github/workflows/pytest.yml
AUTHORS.rst
tests/test_example.ort

- add example
- flake8 the code
- add .gitattributes to normalise line endings
- update AUTHORS.rst

MAINT: add example

---

tests/test_example.ort

Update 'test_example.ort' to match that given at https://www.reflectometry.org/projects/file_formats/tasks/ws_2021-06_text/.

MAINT: update test_example.ort

---

orsopy/fileio/__init__.py
orsopy/fileio/base.py
orsopy/fileio/orso.py
orsopy/schema/refl_header.schema.json
tests/test_example2.ort
tests/test_fileio/test_orso.py
tests/test_fileio/test_schema.py
tools/header_schema.py

This PR is a better method the loading of the ORT dataset into json dictionaries compared to the overall commit state in #16.
- Parses multiple datasets in an ORT file into separate (complete) json dictionaries.
- Amends the validation to work on those separate dictionaries.

ENH: read and parse ORT files

---

.gitignore
orsopy/fileio/__init__.py
orsopy/fileio/base.py
orsopy/fileio/orso.py
tests/test_fileio/test_orso.py
writetest.py

@aglavic, these are some of the changes I suggested to your fromdict branch.

Some suggested changes to the fromdict branch

---

orsopy/fileio/orso.py
tests/test_fileio/test_orso.py

Save a comment in the 2nd line of an Orso file.

ENH: comment in save_orso

---

orsopy/fileio/__init__.py
orsopy/fileio/base.py
orsopy/fileio/orso.py
orsopy/fileio/schema/refl_header.schema.json
tests/test_example.ort
tests/test_example2.ort
tests/test_fileio/test_orso.py
tools/header_schema.py

Removes the `Orso.creator` attribute as discussed on Friday.

MAINT: remove Orso.creator

---

Makefile
docs/conf.py
docs/modules.rst
docs/orsopy.fileio.measurement.rst
orsopy/fileio/orso.py

- Remove a sphinx-construction in makefile
- Remove old files 
- Change to sphinx notation

:DOC: Some documentation improvements 

---

docs/developer_minutes/meeting_2021_11_30.rst
docs/documents.rst
docs/index.rst

Please let me know if there is anything you disagree with or I have forgotten.

Meeting minutes form 2021-11-30

---

orsopy/fileio/base.py
orsopy/fileio/data_source.py
orsopy/fileio/orso.py
orsopy/fileio/reduction.py

Replace metaclass by decorator of same functionality

---

.gitignore
README.rst
docs/index.rst
docs/modules.rst

Made some changes to the documentation ahead of the SXNS conference, so that if people go to the webpage they won't be very confused.

Improvement to documentation 

---

orsopy/fileio/base.py
tests/test_fileio/test_base.py
tests/test_fileio/test_data_source.py
tests/test_fileio/test_orso.py

Proposed solution to #71 that takes care of the signature change in `dataclasses._field_init`.

Fix python 3.10.1 bug

---

HISTORY.rst
orsopy/__init__.py

As discussed we want to use a pull request for any orsopy release.
The main purpose is to allow review of version history/documentation updates and check if an update actually makes sense for the changes merged before.
As we are still in first alpha I will merge this directly, so this is just an example how to do it.

Prepare for release 0.0.4

---

orsopy/dataclasses.py
orsopy/fileio/base.py
orsopy/fileio/data_source.py
orsopy/fileio/orso.py
orsopy/fileio/schema/refl_header.schema.json
orsopy/fileio/schema/refl_header.schema.yaml
tests/test_fileio/test_orso.py
tools/header_schema.py

Generates schema, both JSON and YAML, from the class definitions in orsopy.

Schema generator

---

orsopy/fileio/reduction.py

I noticed that the corrections object was missing from the docstring.

Add corrections of doctoring

---

orsopy/fileio/__init__.py
orsopy/fileio/base.py
orsopy/fileio/data_source.py
orsopy/fileio/orso.py
orsopy/fileio/reduction.py
orsopy/fileio/schema/refl_header.schema.json
orsopy/fileio/schema/refl_header.schema.yaml
tests/test_example.ort
tests/test_example2.ort
tests/test_fileio/test_base.py
tests/test_fileio/test_data_source.py
tests/test_fileio/test_orso.py
tests/test_fileio/test_reduction.py
tools/header_schema.py
writetest.py

As there were no further comments about my proposed changes of the class attributes on Slack I have implemented these as they have been proposed/discussed to prepare for release on the general assembly.

Implement changes discussed on Slack

---

HISTORY.rst
orsopy/__init__.py
setup.cfg

Added comments and updated PyPI to beta.
As discussed on PRs and Slack, this version should be the reference for the discussion and release of the text file standard definition in the upcoming ORSO general assembly

Releas of version 0.1.0

---

.github/workflows/pytest.yml
HISTORY.rst
examples/simple_model_example_3.yml
orsopy/__init__.py
orsopy/dataclasses.py
orsopy/fileio/model_language.py
orsopy/fileio/schema/refl_header.schema.json
orsopy/fileio/schema/refl_header.schema.yaml
tests/test_fileio/test_model_language.py

Prepared the release of the next minor version which includes:
#83 Simple model language implementation ant examples
#94 Small updates to ORT specification

Release version 1.1

---

.github/workflows/pytest.yml
CONTRIBUTING.rst
orsopy/fileio/data_source.py
orsopy/fileio/orso.py
orsopy/slddb/element_table/element.py
orsopy/slddb/material.py

- correct a few typos in the docs
- update contributing docs
- update CI so that it can be run on forked repos (as a test before submitting PR's to reflectometry/orsopy)

pylint, update docs and CI

---

orsopy/fileio/data_source.py
orsopy/fileio/tests/test_data_source.py
orsopy/fileio/tests/test_orso.py

Would close #110 - if we decided it needed "fixing".
@jfkcooper 
@jochenstahn 
@aglavic 
@bmaranville

MAINT: make default polarization - unpolarized

---

CONTRIBUTING.rst
HISTORY.rst
orsopy/__init__.py
orsopy/fileio/base.py
orsopy/fileio/data_source.py
orsopy/fileio/orso.py
orsopy/fileio/schema/refl_header.schema.json
orsopy/fileio/schema/refl_header.schema.yaml
tools/header_schema.py

Jochen asked me to update the orsopy code to include a few new keys and definitions that have been agreed.
Perform minor revision release.

Updates to spec from Jochen/Website

---

HISTORY.rst
orsopy/__init__.py

Release all small changes before general assembly.
I'll merge until Friday, unless there are any objections.

minor version 1.2.1 release

---

orsopy/slddb/tests/test_dbcreation.py

Update test_dbcreation.py to fix linting error

---

.github/workflows/pytest.yml

Replace runner from Ubuntu 20.04 to 22.04

Try to reactivate python 3.6/3.7 backport tests
